export enum IconEnum {
  EDIT = 'edit',
  CHECK = 'check',
  EYE_CROSSED = 'eye-crossed',
  SEARCH = 'search',
  MINUS = 'minus',
  PLUS = 'plus',
  CROSS = 'cross',
  CHEVRON_DOWN = 'chevron-down',
  CHEVRON_RIGHT = 'chevron-right',
  ARROW_LEFT = 'arrow-left',
  STAR = 'star',
  LOCATION = 'location',
  FILTER = 'filter',
  BURGER = 'burger',
}
